spring.application.name=WebBackend
#spring.datasource.url=jdbc:postgresql://db:5432/portfolio_db
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/portfolio_db}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Trusts standard headers (X-Forwarded-For / X-Forwarded-Proto) sent by Nginx container
server.forward-headers-strategy=native

# File Upload Configuration (Crucial for your drag-and-drop feature)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB