spring.application.name=WebBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=joey
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Prints the specific filter that denies the request
logging.level.org.springframework.security=DEBUG

# Prints the SQL queries if your UserDetailsService is failing to find the user
logging.level.org.hibernate.SQL=DEBUG

# (Optional) See the exact data being passed into your UserDetailsService
logging.level.dev.joeyfoxo.webbackend=DEBUG